name: Weekly build

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Determine latest version
        id: latest
        run: |
          url=$(python3 get_latest_rpm_url.py)
          version=$(echo "$url" | sed -n 's/.*bcl-convert-\([0-9.]*\)-2.el7.x86_64.rpm/\1/p')
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if image already exists
        id: check
        run: |
          if docker manifest inspect ctbushman/bcl_convert:${{ steps.latest.outputs.version }} > /dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Download RPM
        if: steps.check.outputs.exists == 'false'
        run: |
          curl -L "${{ steps.latest.outputs.url }}" -o "bcl-convert-${{ steps.latest.outputs.version }}-2.el7.x86_64.rpm"
      - name: Build and push
        if: steps.check.outputs.exists == 'false'
        run: |
          docker build --build-arg BCLCONVERT_VERSION=${{ steps.latest.outputs.version }} -t ctbushman/bcl_convert:${{ steps.latest.outputs.version }} .
          docker push ctbushman/bcl_convert:${{ steps.latest.outputs.version }}
          docker tag ctbushman/bcl_convert:${{ steps.latest.outputs.version }} ctbushman/bcl_convert:latest
          docker push ctbushman/bcl_convert:latest
