name: Build

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Determine latest version
        id: latest
        run: |
          url=$(python3 get_latest_rpm_url.py)
          version=$(echo "$url" | sed -n 's/.*bcl-convert-\([0-9.]*\)-2.el7.x86_64.rpm/\1/p')
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if image already exists
        id: check
        run: |
          if docker manifest inspect ctbushman/bcl_convert:${{ steps.latest.outputs.version }} > /dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Generate manual build instructions
        if: steps.check.outputs.exists == 'false'
        run: |
          VERSION="${{ steps.latest.outputs.version }}"
          URL="${{ steps.latest.outputs.url }}"
          cat <<EOF > MANUAL_BUILD.md
          # Build and push bcl-convert $VERSION

          Download the RPM from the following link (Illumina login required):
          $URL

          Then run the following commands to build and publish the Docker image:

          curl -L "$URL" -o "bcl-convert-$VERSION-2.el7.x86_64.rpm"
          docker build --build-arg BCLCONVERT_VERSION=$VERSION -t ctbushman/bcl_convert:$VERSION .
          docker push ctbushman/bcl_convert:$VERSION
          docker tag ctbushman/bcl_convert:$VERSION ctbushman/bcl_convert:latest
          docker push ctbushman/bcl_convert:latest
          EOF
      - name: Commit instructions
        if: steps.check.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add MANUAL_BUILD.md
          git commit -m "Add manual build instructions for ${{ steps.latest.outputs.version }}"
      - name: Create Pull Request
        if: steps.check.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add manual build instructions for ${{ steps.latest.outputs.version }}"
          title: "Update to bcl-convert ${{ steps.latest.outputs.version }}"
          body: |
            A new version of **bcl-convert** is available.
            Download the RPM from:
            ${{ steps.latest.outputs.url }}

            Instructions to build and push the Docker image are in **MANUAL_BUILD.md**.
          branch: update-${{ steps.latest.outputs.version }}

